site_name: Releases 
repo_name: openinfradev/releases
repo_url: https://github.com/openinfradev/releases
theme:
  language: kr
  name: material
  font:
    text: Noto Sans Korean  
  palette: 
   - scheme: default
     toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
   - scheme: slate 
     toggle:
       icon: material/toggle-switch
       name: Switch to light mode
  features:
    # - navigation.sections
    - navigation.indexes
    - toc.integrate       
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
#    - emoji_index: !!python/name:materialx.emoji.twemoji
#    - emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Welcome: README.md
  - Release Notes: 
    - 1.0.0: releasenotes/README.md
